// src/pages/Searchs/components/songlist.tsx
// import React from 'react'
import { useNavigate } from "react-router-dom"
import { buildPage } from "@/utils/constructdata"

export default function Songlist({ data, idx }: SonglistProps) {
  const Navigate = useNavigate();

  function toPage(item: Song) {
    const path = buildPage(idx);
    Navigate(path + `?id=${item.id || item.videoId}`)
  }

  return (
    <>
      <div className="apps-card">
        {
          data.map((item) => (
            <div className="app-card" key={item.id} onClick={() => toPage(item)}>
              <span>
                <img src={
                  item.picUrl ||
                  item.coverImgUrl ||
                  item.avatarUrl ||
                  item.cover + "?param=430y430"
                } />
              </span>
              <div className="app-card__subtext textoverflow">
                {item.name || item.nickname || item.title}
              </div>
            </div>
          ))
        }
      </div>
    </>
  )
}

// src/pages/search/components/songList.vue
<script setup>
import { songPlaylist } from '@/api/api'
const router = useRouter()
const state = reactive({
	list: [],
	currentPage: 1
})
const {
	list,
	currentPage
} = toRefs(state)

const props = defineProps({
	data: {
		type: Object,
		default: () => []
	}
})

</script>
<template>
	<div>
		<div class="content-section menuBar-mv">
			<div class="apps-card">
				<div class="apps-item" v-for="(item, idx) in props.data" :key="idx"
					@click="router.push({ path: '/playList', query: { id: item.id } })">
					<div class="app-card">
						<img :src="item.coverImgUrl + '?param=200y200'" alt="">
					</div>
					<a href="javascript:;">{{ item.name }}</a>
				</div>
			</div>
		</div>
	</div>
</template>
<style lang='scss' scoped></style>
